Settings: Move telephony-ext to static libs
Attempts to fix:
03-02 10:47:09.482  1389  1389 D AndroidRuntime: Shutting down VM
03-02 10:47:09.483  1389  1389 E AndroidRuntime: FATAL EXCEPTION: main
03-02 10:47:09.483  1389  1389 E AndroidRuntime: Process: com.android.settings, PID: 1389
03-02 10:47:09.483  1389  1389 E AndroidRuntime: java.lang.IllegalArgumentException: The observer class has some methods that use newer APIs which are not available in the current OS version. Lifecycles cannot access even other methods so you should make sure that your observer classes only access framework classes that are available in your min API level OR use lifecycle:compiler annotation processor.
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.lifecycle.ClassesInfoCache.getDeclaredMethods(ClassesInfoCache.java:72)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.lifecycle.ClassesInfoCache.hasLifecycleMethods(ClassesInfoCache.java:50)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.lifecycle.Lifecycling.resolveObserverCallbackType(Lifecycling.java:164)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.lifecycle.Lifecycling.getObserverConstructorType(Lifecycling.java:146)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.lifecycle.Lifecycling.lifecycleEventObserver(Lifecycling.java:83)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:306)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:160)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at com.android.settings.network.telephony.MobileNetworkSwitchController.init(MobileNetworkSwitchController.java:77)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at com.android.settings.network.telephony.MobileNetworkSettings.onAttach(MobileNetworkSettings.java:194)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2869)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:473)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1307)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1477)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1246)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1128)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:135)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2112)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2055)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1957)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3056)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2990)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:458)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at com.android.settings.network.telephony.MobileNetworkActivity.onStart(MobileNetworkActivity.java:177)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8024)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7661)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codeaurora/internal/IExtTelephony;
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at java.lang.reflect.Method.getReturnType(Method.java:148)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at java.lang.Class.getDeclaredMethods(Class.java:1883)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	at androidx.lifecycle.ClassesInfoCache.getDeclaredMethods(ClassesInfoCache.java:70)
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	... 37 more
03-02 10:47:09.483  1389  1389 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: org.codeaurora.internal.IExtTelephony
03-02 10:47:09.483  1389  1389 E AndroidRuntime: 	... 41 more